name: Check SSM Release

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  check_release:

    runs-on: ubuntu-18.04

    steps:
    - name: get latest repository tag
      id: get_latest_tag
      run: |
        repo_tag=$(curl --silent https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/tags | jq '.[-1]')
        echo ::set-output name=repo_tag::${repo_tag}
        echo "::debug::git repository tag ${repo_tag}"
      
    - name: get latest Amazon SSM release
      id: get_latest_ssm_release
      run: |
        ssm_version=$(curl --silent https://api.github.com/repos/aws/amazon-ssm-agent/releases/latest | jq -r .tag_name)
        echo ::set-output name=ssm_version::${ssm_version}
        echo "::debug::ssm latest release ${ssm_version}"
      
    - name: tag repository with latest ssm version if needed
      id: tag_repository
      if: steps.get_latest_tag.outputs.repo_tag != steps.get_latest_ssm_release.outputs.ssm_version
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_PAT_TOKEN }}
        tag: ${{steps.get_latest_ssm_release.outputs.ssm_version}}

        
